### ISSUE TITLE
Restore fails if any of the documents had attachment.

### ISSUE THREAD

**Issue by dphe** [cloudant/couchbackup#147]
Please include the following information in your ticket:

- couchbackup/couchrestore version: "2.0.1-SNAPSHOT"
- Node.js version: v6.2.0
- A sample of the code or command line statement that demonstrates the issue.
```
 couchbackup.restore(data_stream, url, {parallelism: params.couchbackup.parallelism},
                            function (err, data) {});
```
Error:
If properly handled:
```
info: Restore for DB 'test_status' failed due to errors - HTTPFatalError: 412 Precondition Failed: POST https://xxxxx.cloudant.com/test_status/_bulk_docs - Error: missing_stub, Reason: Invalid attachment stub in 0077150069D1G79LL20 for test5.html
```

if Error not handled:

```
/node_modules/@cloudant/couchbackup/includes/restore.js:30
        readstream.destroy();
                   ^

TypeError: readstream.destroy is not a function
    at Transform.errHandler (/node_modules/@cloudant/couchbackup/includes/restore.js:30:20)
    at emitOne (events.js:101:20)
    at Transform.emit (events.js:188:7)
    at Object.taskCallback [as callback] (/node_modules/@cloudant/couchbackup/includes/writer.js:75:16)
    at /node_modules/async/dist/async.js:2244:31
    at /node_modules/async/dist/async.js:906:16
    at Request._callback (/node_modules/@cloudant/couchbackup/includes/writer.js:53:9)
    at Request.self.callback (/node_modules/request/request.js:188:22)
```

Probably the better way to handle this would be to:

```
readstream.emit('end');
```

**Comment by ricellis** [comment]
Yes, it looks like `readstream.destroy([err])` was only added in version 8 of Node.js so we shouldn't be using it. Clearly we're also lacking a CI test for this path.

Whilst this error handling does need correction also just to clarify that `couchbackup` does not support attachments, hence the error.
