### ISSUE TITLE
ERROR: Parameter "url" must be a string not "object"

### ISSUE THREAD

**Issue by apostoa** [cloudant/couchbackup#187]
Please include the following information in your ticket:

- couchbackup/couchrestore version(s) that are affected by this issue.
        -  run s3-backup-stream.js script from the release tag in the tree

- Node.js version.
v8.9.4

- A sample of the code or command line statement that demonstrates the issue.
    I get this erorr :

 throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at main (/home/oanaapostol/Desktop/Backup-restore/Project/cloudant-backup-restore/app/s3-backup-stream.js:50:26)
    at Object.<anonymous> (/home/oanaapostol/Desktop/Backup-restore/Project/cloudant-backup-restore/app/s3-backup-stream.js:176:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)

**Comment by tomblench** [comment]
@apostoa what options did you use when you ran the script?

**Comment by tomblench** [comment]
@apostoa you need to use `--s3url` (note the two minus characters)

**Comment by tomblench** [comment]
also note that it needs to be a full URL (including http or https)

**Comment by apostoa** [comment]
Hello Tom,
I used --s3url. No error appears now but nothing happens actually, no backup is done.

**Comment by tomblench** [comment]
Any output or errors?

**Comment by apostoa** [comment]
I put on DEBUG=* and it hits me with this error: "Inaccessible host: XXXXXX.xyz.ibm.objstor.com'. This service may not be available in the us-east-1' region". The COS i am trying to access is Cleversafe type. In the ~/aws/config the region is set to DE.

**Comment by tomblench** [comment]
I wonder why the error mentions `us-east-1`, that sounds like an AWS region. Do you have some AWS specific entries under the `default` profile? You probably need to create a profile which is COS specific and set that using the `--awsprofile` flag.

You can see more documentation [here](https://ibm-public-cos.github.io/crs-docs/cli), it looks like the note about `LocationConstraint` note is relevant.
