### ISSUE TITLE
Getting toString() failed

### ISSUE THREAD

**Issue by jungalwala** [cloudant/couchbackup#208]
couchbackup/couchrestore version = 2.1.0
node.js = 8.9.4
command: `( node_modules/@cloudant/couchbackup/bin/couchbackup.bin.js --url="http://xxxx:yyyy@localhost:5984/" --db="checklists" | gzip > checklists.txt.gz ) >& checklists.log`

I get the following error when trying to backup our 'checklists' database (13.2GB and 1048 docs):

```
================================================================================
Performing backup on http://****:****@localhost:5984/checklists using configuration:
{
  "bufferSize": 500,
  "log": "/tmp/tmp-12732a9XEbt8f6XtM.tmp",
  "mode": "full",
  "parallelism": 5
}
================================================================================
2018-03-05T22:50:06.424Z couchbackup:backup Fetching all database changes...
2018-03-05T22:50:06.496Z couchbackup:backup Total batches received: 1
2018-03-05T22:50:06.511Z couchbackup:backup Total batches received: 2
2018-03-05T22:50:06.517Z couchbackup:backup Total batches received: 3
buffer.js:556
  if (encoding === undefined) return buf.utf8Slice(start, end);
                                         ^
Error: "toString()" failed
    at stringSlice (buffer.js:556:42)
    at Buffer.toString (buffer.js:633:10)
    at Request.<anonymous> (/root/couchdb-tools/node_modules/request/request.js:1137:39)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.self._source.emit (/root/couchdb-tools/node_modules/@cloudant/cloudant/lib/eventrelay.js:78:21)
    at IncomingMessage.<anonymous> (/root/couchdb-tools/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
```

**Comment by smithsz** [comment]
Hi, This bug sounds very familiar to one we've just squashed in the latest 2.2.0 release.
Please can you retry your backup using `@cloudant/couchbackup@2.2.0`?
Let me know how you get on.
Thanks,
Sam

**Comment by ricellis** [comment]
>13.2GB and 1048 docs

It looks like your document size and the default document batch size (`--buffer-size`) of 500 are resulting in HTTP response data (~6 GB) that exceeds the maximum Node.js `Buffer` size in the Node requests library. 

This is similar problem to your previous issue #203 - you need to reduce couchbackup's `--buffer-size` parameter or `COUCH_BUFFER_SIZE` environment variable to reduce the number of documents fetched in a single request.

FWIW this also suggests that you have some very large documents. I suggest you take a look at the [Cloudant best and worst practices blog post](https://medium.com/ibm-watson-data-lab/cloudant-best-and-worst-practices-7ee2040da1b).

**Comment by jungalwala** [comment]
I bumped the `--max_old_space_size=8192` and the `--buffer-size=5`.  It is bummer that Buffer can do more than 256MB.
